// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/io_mssql_version.test.ts.

/** The version of the `@rljson/io-mssql` package. */
export const ioMssqlVersion = '0.0.31';
