name: Create Container
on:
  workflow_dispatch:
jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install

      - name: Create Docker container
        run: |
          docker build -t my-node-app .
          docker run -d -p 3000:3000 --name my-running-app my-node-app

      - name: Verify container is running
        run: docker ps | grep my-running-app
      - name: Test application endpoint
        run: |
          sleep 10 # Wait for the app to start
          curl -f http://localhost:3000 || exit 1
      - name: Stop and remove container
        run: |
          docker stop my-running-app
          docker rm my-running-app
